/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AiSettingSchema extends BaseModel {
  static $columns = ['createdAt', 'featureKey', 'id', 'isEnabled', 'maxTokens', 'model', 'temperature', 'updatedAt', 'value'] as const
  $columns = AiSettingSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare featureKey: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isEnabled: boolean
  @column()
  declare maxTokens: number
  @column()
  declare model: string
  @column()
  declare temperature: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare value: any | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BlockedEntitySchema extends BaseModel {
  static $columns = ['blockedUntil', 'createdAt', 'entityId', 'entityType', 'id', 'reason', 'updatedAt', 'userId'] as const
  $columns = BlockedEntitySchema.$columns
  @column.dateTime()
  declare blockedUntil: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare entityId: string
  @column()
  declare entityType: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare reason: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class CandidateProfileSchema extends BaseModel {
  static $columns = ['createdAt', 'cvFilePath', 'cvText', 'experienceYears', 'followUps', 'id', 'onboardingCompleted', 'preferences', 'recontactCooldownDays', 'sendingSchedule', 'skills', 'targetCountries', 'targetRoles', 'targetSectors', 'updatedAt', 'userId'] as const
  $columns = CandidateProfileSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cvFilePath: string | null
  @column()
  declare cvText: string | null
  @column()
  declare experienceYears: number
  @column()
  declare followUps: any | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare onboardingCompleted: boolean
  @column()
  declare preferences: any | null
  @column()
  declare recontactCooldownDays: number
  @column()
  declare sendingSchedule: any | null
  @column()
  declare skills: any
  @column()
  declare targetCountries: any
  @column()
  declare targetRoles: any
  @column()
  declare targetSectors: any
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class CompanySchema extends BaseModel {
  static $columns = ['city', 'country', 'createdAt', 'domain', 'hiringIntensity', 'id', 'linkedinUrl', 'name', 'sector', 'signals', 'size', 'source', 'teamCrawledAt', 'updatedAt', 'visaRegistryCheckedAt', 'visaSponsorCountries', 'visaSponsorStatus', 'website'] as const
  $columns = CompanySchema.$columns
  @column()
  declare city: string | null
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare domain: string | null
  @column()
  declare hiringIntensity: number | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare linkedinUrl: string | null
  @column()
  declare name: string
  @column()
  declare sector: string | null
  @column()
  declare signals: any | null
  @column()
  declare size: string | null
  @column()
  declare source: string
  @column.dateTime()
  declare teamCrawledAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare visaRegistryCheckedAt: DateTime | null
  @column()
  declare visaSponsorCountries: any | null
  @column()
  declare visaSponsorStatus: string | null
  @column()
  declare website: string | null
}

export class ContactMovementSchema extends BaseModel {
  static $columns = ['contactId', 'createdAt', 'fromStatus', 'id', 'toStatus', 'trigger'] as const
  $columns = ContactMovementSchema.$columns
  @column()
  declare contactId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare fromStatus: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare toStatus: string
  @column()
  declare trigger: string
}

export class ContactSchema extends BaseModel {
  static $columns = ['aiRecommendation', 'companyId', 'cooldownUntil', 'createdAt', 'email', 'emailAlternatives', 'emailConfidence', 'emailSource', 'emailStatus', 'fullName', 'githubUrl', 'id', 'lastContactedAt', 'linkedinUrl', 'relevanceLabel', 'relevanceReason', 'relevanceScore', 'role', 'scoreBreakdown', 'scoreVersion', 'source', 'sourceDetail', 'sourcingRunId', 'status', 'updatedAt', 'userId', 'userOverride'] as const
  $columns = ContactSchema.$columns
  @column()
  declare aiRecommendation: string | null
  @column()
  declare companyId: string
  @column.dateTime()
  declare cooldownUntil: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column()
  declare emailAlternatives: any | null
  @column()
  declare emailConfidence: number | null
  @column()
  declare emailSource: string | null
  @column()
  declare emailStatus: string | null
  @column()
  declare fullName: string
  @column()
  declare githubUrl: string | null
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare lastContactedAt: DateTime | null
  @column()
  declare linkedinUrl: string | null
  @column()
  declare relevanceLabel: string | null
  @column()
  declare relevanceReason: string | null
  @column()
  declare relevanceScore: number | null
  @column()
  declare role: string
  @column()
  declare scoreBreakdown: any | null
  @column()
  declare scoreVersion: string | null
  @column()
  declare source: string
  @column()
  declare sourceDetail: string | null
  @column()
  declare sourcingRunId: string | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
  @column()
  declare userOverride: boolean
}

export class EmailConnectionSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'imapHost', 'imapPassword', 'imapPort', 'imapUser', 'isActive', 'lastSyncedAt', 'smtpHost', 'smtpPassword', 'smtpPort', 'smtpUser', 'updatedAt', 'userId'] as const
  $columns = EmailConnectionSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare imapHost: string
  @column()
  declare imapPassword: string
  @column()
  declare imapPort: number
  @column()
  declare imapUser: string
  @column()
  declare isActive: boolean
  @column.dateTime()
  declare lastSyncedAt: DateTime | null
  @column()
  declare smtpHost: string
  @column()
  declare smtpPassword: string
  @column()
  declare smtpPort: number
  @column()
  declare smtpUser: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class EmailMessageSchema extends BaseModel {
  static $columns = ['body', 'contactId', 'createdAt', 'id', 'openedAt', 'repliedAt', 'scheduledAt', 'sentAt', 'status', 'subject', 'type', 'updatedAt'] as const
  $columns = EmailMessageSchema.$columns
  @column()
  declare body: string
  @column()
  declare contactId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare openedAt: DateTime | null
  @column.dateTime()
  declare repliedAt: DateTime | null
  @column.dateTime()
  declare scheduledAt: DateTime | null
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare subject: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EmailReplySchema extends BaseModel {
  static $columns = ['aiSummary', 'bodyHtml', 'bodyText', 'contactId', 'createdAt', 'detectedEvent', 'emailMessageId', 'fromEmail', 'id', 'isRead', 'receivedAt', 'subject', 'updatedAt', 'userId'] as const
  $columns = EmailReplySchema.$columns
  @column()
  declare aiSummary: string | null
  @column()
  declare bodyHtml: string | null
  @column()
  declare bodyText: string | null
  @column()
  declare contactId: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare detectedEvent: string | null
  @column()
  declare emailMessageId: string | null
  @column()
  declare fromEmail: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isRead: boolean
  @column.dateTime()
  declare receivedAt: DateTime
  @column()
  declare subject: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class EmailTemplateSchema extends BaseModel {
  static $columns = ['bodyPattern', 'createdAt', 'id', 'isDefault', 'name', 'subjectPattern', 'updatedAt', 'userId'] as const
  $columns = EmailTemplateSchema.$columns
  @column()
  declare bodyPattern: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isDefault: boolean
  @column()
  declare name: string
  @column()
  declare subjectPattern: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class ExternalCacheSchema extends BaseModel {
  static $columns = ['createdAt', 'data', 'entityKey', 'entityType', 'expiresAt', 'fetchedAt', 'id', 'source', 'updatedAt'] as const
  $columns = ExternalCacheSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare data: any
  @column()
  declare entityKey: string
  @column()
  declare entityType: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column.dateTime()
  declare fetchedAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare source: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class FollowUpSequenceSchema extends BaseModel {
  static $columns = ['createdAt', 'delayDays1', 'delayDays2', 'delayDays3', 'id', 'updatedAt', 'userId'] as const
  $columns = FollowUpSequenceSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare delayDays1: number
  @column()
  declare delayDays2: number
  @column()
  declare delayDays3: number
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class GenerationPresetSchema extends BaseModel {
  static $columns = ['createdAt', 'customInstructions', 'framework', 'id', 'isDefault', 'language', 'length', 'name', 'tone', 'updatedAt', 'userId'] as const
  $columns = GenerationPresetSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customInstructions: string | null
  @column()
  declare framework: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isDefault: boolean
  @column()
  declare language: string
  @column()
  declare length: string
  @column()
  declare name: string
  @column()
  declare tone: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class SearchRunSchema extends BaseModel {
  static $columns = ['completedAt', 'contactsExcludedCooldown', 'contactsFound', 'contactsRelevant', 'country', 'createdAt', 'currentStep', 'emailsGenerated', 'errorMessage', 'id', 'progressPercent', 'sector', 'sourcingRunId', 'startedAt', 'status', 'updatedAt', 'userId'] as const
  $columns = SearchRunSchema.$columns
  @column.dateTime()
  declare completedAt: DateTime | null
  @column()
  declare contactsExcludedCooldown: number
  @column()
  declare contactsFound: number
  @column()
  declare contactsRelevant: number
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare currentStep: string | null
  @column()
  declare emailsGenerated: number
  @column()
  declare errorMessage: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare progressPercent: number
  @column()
  declare sector: string | null
  @column()
  declare sourcingRunId: string | null
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class SourcingRunSchema extends BaseModel {
  static $columns = ['completedAt', 'contactsFound', 'country', 'createdAt', 'errors', 'id', 'sector', 'sources', 'startedAt', 'status', 'updatedAt', 'userId'] as const
  $columns = SourcingRunSchema.$columns
  @column.dateTime()
  declare completedAt: DateTime | null
  @column()
  declare contactsFound: number
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare errors: any | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare sector: string | null
  @column()
  declare sources: any
  @column.dateTime()
  declare startedAt: DateTime | null
  @column()
  declare status: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column()
  declare userId: string
}

export class SourcingSourceSchema extends BaseModel {
  static $columns = ['baseUrl', 'config', 'country', 'createdAt', 'enabled', 'id', 'name', 'scraperClass', 'updatedAt'] as const
  $columns = SourcingSourceSchema.$columns
  @column()
  declare baseUrl: string
  @column()
  declare config: any | null
  @column()
  declare country: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare enabled: boolean
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare scraperClass: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'isAdmin', 'locale', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isAdmin: boolean
  @column()
  declare locale: string
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class VisaSponsorRegistrySchema extends BaseModel {
  static $columns = ['accreditedSince', 'companyName', 'companyNameNormalized', 'country', 'id', 'indexedAt', 'rawData', 'sourceUrl', 'visaType'] as const
  $columns = VisaSponsorRegistrySchema.$columns
  @column.date()
  declare accreditedSince: DateTime | null
  @column()
  declare companyName: string
  @column()
  declare companyNameNormalized: string
  @column()
  declare country: string
  @column({ isPrimary: true })
  declare id: string
  @column.dateTime()
  declare indexedAt: DateTime
  @column()
  declare rawData: any | null
  @column()
  declare sourceUrl: string | null
  @column()
  declare visaType: string
}
